version: '3'

services:
  frontend:
    container_name: track-finance-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    networks:
      - trackfinannet
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn run dev"
    tty: true

networks:
  trackfinannet:
    driver: bridge
