name: cd-track-finance-admin-workflow

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

  build-image:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: track-finance-admin/app:latest

  push-image:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            venilson/track-finance-admin:latest
            venilson/track-finance-admin:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: push-image

  #   steps:
  #     - name: Deploy to homelab
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SERVER_KEY }}
  #         script: |
  #           docker pull track-finance-api/app:latest

  #           docker stop track-finance-api || true
  #           docker rm track-finance-api || true

  #           docker run -d --name track-finance-api \
  #             -p 3000:3000 \
  #             track-finance-api/app:latest
              